### ISSUE TITLE
API Key is not recognized even though I can use it to log in via Docker

### ISSUE THREAD

**Issue by blairjj** [NVIDIA/ngc-container-replicator#15]
Error:
local$ docker run --rm -it -v /var/run/docker.sock:/var/run/docker.sock -v /tmp:/output deepops/replicator --project=nvidia --min-version=17.12 --image=tensorflow --image=pytorch --image=tensorrt --dry-run --api-key=<my API key>
2020-08-28 02:46:19,202 - ngc_replicator.ngc_replicator - 30 - INFO - Initializing Replicator
Traceback (most recent call last):
  File "/usr/local/bin/ngc_replicator", line 11, in <module>
    load_entry_point('ngc-replicator==0.4.0', 'console_scripts', 'ngc_replicator')()
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/ngc_replicator-0.4.0-py3.6.egg/ngc_replicator/ngc_replicator.py", line 346, in main
    replicator = Replicator(**config)
  File "/usr/local/lib/python3.6/site-packages/ngc_replicator-0.4.0-py3.6.egg/ngc_replicator/ngc_replicator.py", line 39, in __init__
    raise RuntimeError("Unable to recognize the API key")
RuntimeError: Unable to recognize the API key

Steps to reproduce:

1) Log into NGC and get new API Key
2) Test key by using docker to login:
     a) docker login nvcr.io
     b) username: $oauthtoken
     c) Password: (my new API key from 1)
3) Login was successful and API key was accepted
4) Run sample command from the github site using same exact API key in 1 and 2:
docker run --rm -it -v /var/run/docker.sock:/var/run/docker.sock -v /tmp:/output deepops/replicator --project=nvidia --min-version=17.12 --image=tensorflow --image=pytorch --image=tensorrt --dry-run --api-key=<my API key>

**Comment by dholt** [comment]
Should be fixed in #16
